gx_theme:
  name: "Catppuccin for Opera GX",
  description: "Soothing pastel theme for Opera GX",
  developer:
    name": "Catppuccin"
    version": "1.0"
    icons:
      512: "icon_512.png"
    manifest_version: 3
    mod:
      license: "license.txt"
      payload:
        theme:
          dark:
            gx_accent: *accent
            gx_secondary_base: *base
          light:
            gx_accent: *accent
            gx_secondary_base: *base
        wallpaper:
          dark:
            image: "wallpaper/macchiato.png"
            text_color: *text
            text_shadow: *crust
          light:
            image: "wallpaper/macchiato.png"
            text_color": *text
            text_shadow": *crust
      schema_version": 1
